Merging things from prebuild branch

diff --git a/.github/workflows/prebuild.yaml b/.github/workflows/prebuild.yaml
--- a/.github/workflows/prebuild.yaml
+++ b/.github/workflows/prebuild.yaml
@@ -47,7 +47,7 @@ jobs:
       - name: Build
         run: |
           install-node-gyp
-          source $(which cross-env) ${{ matrix.arch }}
+          . $(which cross-env) ${{ matrix.arch }}
           npm install --ignore-scripts
           . prebuild/Linux/preinstall.sh
           cp prebuild/Linux/binding.gyp binding.gyp
@@ -71,7 +71,7 @@ jobs:
         run: . prebuild/tarball.sh
 
       - name: Upload
-        uses: actions/github-script@0.9.0
+        uses: actions/github-script@v2
         with:
           script: |
             const fs = require("fs");
@@ -142,7 +142,7 @@ jobs:
         run: . prebuild/tarball.sh
 
       - name: Upload
-        uses: actions/github-script@0.9.0
+        uses: actions/github-script@v2
         with:
           script: |
             const fs = require("fs");
@@ -178,35 +178,55 @@ jobs:
         node: [8, 9, 10, 11, 12, 13, 14, 16, 18, 20]
         canvas_tag: ["master"] # e.g. "v2.6.1"
     name: ${{ matrix.canvas_tag}}, Node.js ${{ matrix.node }}, Windows
-    runs-on: windows-latest
+    runs-on: windows-2019
     env:
       CANVAS_VERSION_TO_BUILD: ${{ matrix.canvas_tag }}
     steps:
-      # TODO drop when https://github.com/actions/virtual-environments/pull/632 lands
-      - uses: numworks/setup-msys2@v1
+      # GitHub runners now have msys2 installed, but msys is not on the path and
+      # is apparently slow to start.
+      # https://github.com/msys2/setup-msys2#setup-msys2
+      # https://github.com/actions/virtual-environments/pull/632
+      - uses: msys2/setup-msys2@v1
         with:
+          msystem: UCRT64
           update: true
           path-type: inherit
 
-      - uses: actions/setup-node@v1
+      - uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node }}
 
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           ref: ${{ matrix.canvas_tag }}
+          fetch-depth: 0
 
       - name: Build
         run: |
-          msys2do bash prebuild/Linux/gyp.sh
-          msys2do npm install --ignore-scripts
-          msys2do . prebuild/Windows/preinstall.sh
-          msys2do cp prebuild/Windows/binding.gyp binding.gyp
-          msys2do node-gyp configure
-          msys2do node-gyp rebuild -j 2
+          msys2 -c ". prebuild/Linux/gyp.sh"
+          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
+          npm install --ignore-scripts
+          msys2 -c ". prebuild/Windows/preinstall.sh"
+          msys2 -c "cp prebuild/Windows/binding.gyp binding.gyp"
+          npm install --build-from-source
 
-      - name: Bundle
-        run: msys2do . prebuild/Windows/bundle.sh
+      - name: Install Depends
+        run: |
+          Invoke-WebRequest "http://www.dependencywalker.com/depends22_x64.zip" -OutFile depends22_x64.zip
+          7z e depends22_x64.zip
+
+      - name: Bundle pt 2
+        shell: msys2 {0}
+        run: |
+          ./depends.exe -c -oc depends.csv build\\Release\\canvas.node || true
+          [ -f depends.csv ] || { echo "error invoking depends.exe"; exit 1; }
+          copies=$(comm -12 \
+            <(cat depends.csv | cut -d ',' -f2 | sed 's/"//g' | tr '[:upper:]' '[:lower:]' | sort) \
+            <(find /ucrt64/bin -name '*.dll' -printf "%f\n" | tr '[:upper:]' '[:lower:]' | sort) \
+          )
+          for dll in $copies; do
+            cp /ucrt64/bin/$dll build/Release
+          done;
 
       - name: Test binary
         # By not running in msys2, this doesn't have access to the msys2 libs
@@ -215,10 +235,10 @@ jobs:
       - name: Make asset
         id: make_bundle
         # I can't figure out why this isn't an env var already. It shows up with `env`.
-        run: msys2do UPLOAD_TO=${{ env.UPLOAD_TO }} CANVAS_VERSION_TO_BUILD=${{ env.CANVAS_VERSION_TO_BUILD}} . prebuild/tarball.sh
+        run: msys2 -c "UPLOAD_TO=${{ env.UPLOAD_TO }} CANVAS_VERSION_TO_BUILD=${{ env.CANVAS_VERSION_TO_BUILD}} . prebuild/tarball.sh"
 
       - name: Upload
-        uses: actions/github-script@0.9.0
+        uses: actions/github-script@v2
         with:
           script: |
             const fs = require("fs");
